matrix:
    include:

        language: ruby

        rvm:
        - 2.5.1

        env:
        - db: localhost

        addons:
        hosts:
        - db

        install:
        - cd indicaAi
        - gem install bundler
        - bundler install

        before_script:
        - rake db:create
        - rake db:migrate

        script:
        - bundle exec rspec

        language: node_js
        node_js:
        - '8'
        branches:
        only:
        - devel
        cache:
        directories:
        - node_modules
        before_install:
        - npm update
        install:
        - npm install
        script:
        - npm test
        - npm run coveralls

notifications:
    slack: indicaai:g0c69S8I2cLnQHEM5FAhlaUB

